### ISSUE TITLE
Update puppetdb SSL cert

### ISSUE THREAD

**Issue by carlio** [akvo/akvo-provisioning#117]
The SSL certificate for the localdev puppetdb server will expire next month. This is the one used on the Vagrant boxes

**Comment by orifito** [comment]
Certs expiration date:
```notAfter=Apr  8 12:26:32 2015 GMT```
:hushed:

**Comment by orifito** [comment]
Puppetdb certificates have been updated in all servers.
New validity:
```
            Not Before: Apr  8 07:28:28 2015 GMT
            Not After : Apr  5 07:28:28 2025 GMT
```
We already had a similar validity (10 years) for the localdev puppetdb server:
```
            Not Before: Nov 11 09:42:01 2014 GMT
            Not After : Nov  8 09:42:01 2024 GMT
```
