### ISSUE TITLE
Reporting.akvo.org - backup

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#133]
As the current machine at Hetzner will be used until the production server is correctly setup, we need to ensure work on the current machine is being backed up.

**Comment by carlio** [comment]
@Lynngre @zzgvh Could you let me know what databases and data needs to be backed up please?

**Comment by zzgvh** [comment]
Report server is run from /var/lib/tomcat7/webapps/reportserver. Most of it is static, but we've added a couple of patches etc so it'd be good be be able to just unfold it again if needed.

And then there's the Postgres DB. Back up in full plz, most of ReportServer data lives there.

Finally I'd like to backup /home/gabriel for now. I'm running Drake there so there is some stuff that'd be nice to keep if the server goes pear shaped.
