### ISSUE TITLE
Add provisioning for public data server

### ISSUE THREAD

**Issue by osgl** [akvo/akvo-provisioning#135]
Automated provisioning of ckan. We also need to setup ssl on nginx sitting in front of ckan application

**Comment by orifito** [comment]
Live ckan server has been provisioned with a basic installation (version 2.3)

**Comment by orifito** [comment]
Daily backups should be working from now on, default script at ckan module had to be adapted. In addition, backups will be stored on common path for them, so they are aligned with the whole backup process.

**Comment by orifito** [comment]
Wrong id in above reference, maybe working too much on this one :smile:

**Comment by orifito** [comment]
HTTPS has been enabled on live server :dancers:

**Comment by Lynngre** [comment]
Fantastic.  Thank you.

**Comment by orifito** [comment]
Need to give sudo rights to Lynn
