### ISSUE TITLE
Diskspace increase for upgrade - Piwik server

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#153]
Piwik support are upgrading the installation on analytics.akvo.org on Thursday and have requested an additional 20Gb be ordered, which has been done.

I'll also followup with them re what is safe for us to delete/why Piwik takes so much disk space.

**Comment by Lynngre** [comment]
Upgraded, but seems backup is full.  @osgl & @orifito will let me know how to move ahead once various issues have been checked.

**Comment by orifito** [comment]
We were able to free up some disk space (roughly 12GB), and the data is being backed up daily to our backupserver at Hetzner infrastructure.

**Comment by orifito** [comment]
Currently the server has roughly 70GB of free disk space.
