### ISSUE TITLE
RSR sync data commands in TeamCity are broken

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-provisioning#162]
- Test: psql is not installed
- UAT: SSH credentials are outdated

See http://ci.akvo.org/project.html?projectId=RSR_SyncData

**Comment by orifito** [comment]
`Sync Data` TeamCity job for RSR is now working at both test and UAT

**Comment by KasperBrandt** [comment]
Tables are not dropped before the sync, causing errors in the sync:

```ERROR:  relation "auth_group_id_seq" already exists```

**Comment by orifito** [comment]
It seems there is a easy way to do so:
```
run DELETE SCHEMA public CASCADE;
then CREATE SCHEMA public;
```
Waiting for @KasperBrandt's notification to apply changes into test environment.

**Comment by orifito** [comment]
Now we drop and create the `public` schema each time we want to synhcronize DB from live to test or uat environments. Moreover we modified an script to synchronize all media data, including the cached one.
