### ISSUE TITLE
Set up Keycloak provisioning

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-provisioning#183]
- [x] Download distribution to files.support.akvo-ops.org from sourceforge
- [x] Verify checksum
- [x] Create Puppet module
- [ ] Test deployment

**Comment by stellanl** [comment]
Puppet will not deploy to server test6, because of this error: 
[141.138.197.208] out: Error: Could not find dependency Package[npm] for Exec[npm_proxy] at /puppet/checkout/puppet/ext/nodejs/manifests/init.pp:125

Nodejs is included by the statsd module, which is deployed to all servers. However, it only fails on test6.

**Comment by stellanl** [comment]
Deploy even fails after removing the keycloak module entirely.

**Comment by stellanl** [comment]
With he new nodejs and apt modules, deploy fails for lack of the python-software-properties command. After adding that manually, the deploy succeeds.

**Comment by stellanl** [comment]
test6 server now answers, using the postgres database on test2

**Comment by stellanl** [comment]
Have tested all combinations of these config parameters for supervisord, in file /etc/supervisor/conf.d/keycloak.conf:

environment=LAUNCH_JBOSS_IN_BACKGROUND="true"
stopasgroup=true
stopsignal= KILL

...but "supervisorctl stop keycloak" still only stops the standalone.sh process, not the java server it started.
When run from a terminal, it stops nicely on a Ctrl-C.

**Comment by iperdomo** [comment]
@osgl @peeb do we have a time frame to have the test server?

**Comment by stellanl** [comment]
This has clearly been overtaken by #221
