### ISSUE TITLE
New WordPress Multisites server

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#185]
Required for running the new Akvo Sites templates from z&z with Laura

**Comment by orifito** [comment]
Tentative requirements: 
* PHP >= 5.4
* adapt wp-config.php and nginx configuration if needed

**Comment by orifito** [comment]
We need to add a new wordpress installation on live server already hosting current production akvosites. It will host those existing sites once migrated to use new template from Z&Z.

**Comment by Lynngre** [comment]
Decision was taken at a later meeting to provision a new live server for the new template Akvo Sites as the old ones will not be migrated over (many have consortium contracts running out in the near future) & it could cause issues with diff versions of php, mysql & wordpress.  @peeb @orifito please keep us updated on the provisioning of that new server/what you need from me.

**Comment by orifito** [comment]
Live installation running new akvosites Z&Z template has been already provisioned and configured :fast_forward: :fast_forward: :fast_forward: :fast_forward: 
Remaining steps: 
* Update domains configuration:
  * live env: sites.akvo.org as the primary domain (this is done), and akvosites.akvo.org for the live sites demo portal
  * test env: sites.akvotest.org as the primary domain, and akvosites.akvotest.org for the test sites demo portal
* Setup appropriate php-fpm configuration

**Comment by orifito** [comment]
@Lynn from now on let's use domains mentioned above
