### ISSUE TITLE
Update nodejs module to 1.1.0

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-provisioning#197]
There are strange things wrt npm_proxy in our current release.

**Comment by stellanl** [comment]
With he new nodejs and apt modules, deploy fails for lack of the python-software-properties package. After adding that manually, the deploy succeeds on test6.

**Comment by orifito** [comment]
The package resource for 'python-software-properties' has been added https://github.com/akvo/akvo-provisioning/blob/3c803d75e836e03f25327513c0d64a3915bc4882/puppet/modules/common/manifests/repos.pp#L16-L18
