### ISSUE TITLE
Team City data sync fails

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#203]
The data sync from akvo.org's live database to akvouat.org is failing with exit code 255.  The data sync from akvo.org's live database to akvodev.org works fine.

![screen shot 2015-08-19 at 09 19 48](https://cloud.githubusercontent.com/assets/2675262/9350747/97994fd6-4653-11e5-83eb-770e84eab330.png)
![screen shot 2015-08-19 at 09 19 56](https://cloud.githubusercontent.com/assets/2675262/9350758/ac704d6a-4653-11e5-9af0-937c3f3a336d.png)

**Comment by orifito** [comment]
Solved :dancers:
