### ISSUE TITLE
SSH for Andreas (Kreablo)

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#214]
Please provide ssh access for the developer, Andreas, to akvosites.test.akvo-ops.org for Akvo Sites ZZ theme updates testing.

**Comment by orifito** [comment]
@Lynngre we need his ssh pub key for that

**Comment by orifito** [comment]
@Lynn user 'andreas' has been added to akvosites test server (i.e. sites.akvotest.org)

**Comment by Lynngre** [comment]
@orifito please update Andreas's ssh user to have 'write' permissions on the 'code' directory for sites.akvotest.org

**Comment by orifito** [comment]
@Lynngre from now on Andreas has write permissions on `code` directory

**Comment by Lynngre** [comment]
Thank you!
