### ISSUE TITLE
Read only PostgreSQL user

### ISSUE THREAD

**Issue by peeb** [akvo/akvo-provisioning#215]
It will be important, moving forward, to have a read-only postgres user for products such as report server and Dash.

**Comment by stellanl** [comment]
I found this useful:
http://stackoverflow.com/questions/760210/how-do-you-create-a-read-only-user-in-postgresql

**Comment by stellanl** [comment]
I hand-created a rsr_readonly user on psql.test using these commands, and it works well for reporting:

sudo -u postgres psql
postgres=#  create role rsr_readonly encrypted password '*************' login;
postgres=# grant connect on database rsr to rsr_readonly;
\c rsr
rsr=# grant usage on schema public to rsr_readonly;
rsr=# grant select on all tables in schema public to rsr_readonly;
rsr=# grant select on all sequences in schema public to rsr_readonly;

**Comment by stellanl** [comment]
Does not look like Paul ever got around to this. It would be good to have in the Puppet module so that it does not have to be created by hand...
