### ISSUE TITLE
CartoDB Docker Container

### ISSUE THREAD

**Issue by peeb** [akvo/akvo-provisioning#218]
We have decided to go down the route of dockerising individual components of the CartoDB  platform.

This currently comprises of the following containers:

Generic containers usable elsewhere in the Akvo Platform:

* PostgreSQL with PostGIS extensions
* Redis
* nginx
* varnish

Specific CartoDB container(s):

* Node.js running ... (details?)
* Ruby on Rails running ... (details?)
* [Resque](https://github.com/resque/resque)

This issue is intended to be a starting point for generating work.

**Comment by orifito** [comment]
Basic info on specific CartoDB components:
* PostgreSQL [cartodb](https://github.com/CartoDB/cartodb-postgresql) extension
* NodeJS apps:
 * [CartoDB SQL API](https://github.com/CartoDB/CartoDB-SQL-API)
 * [Windshaft](https://github.com/CartoDB/Windshaft-cartodb)
* Rails app:
 * [CartoDB](https://github.com/CartoDB/cartodb)

**Comment by orifito** [comment]
It seems we have a first version of a dockerized CartoDB platform, so I'm closing this issue and let's open individual & small ones for any new feature or bug fix

**Comment by peeb** [comment]
:+1:
