### ISSUE TITLE
Update SSL certificates

### ISSUE THREAD

**Issue by orifito** [akvo/akvo-provisioning#220]
We must reprovision staging and live unilog hosts to use new certificate, as well as on peak and mockups server

**Comment by Lynngre** [comment]
@orifito peak is still showing the incorrect SSL cert.

**Comment by orifito** [comment]
@Lynngre it is showing the right one for me

**Comment by Lynngre** [comment]
Thanks @orifito maybe it's just my browser caching.  Will check again.

**Comment by orifito** [comment]
We also need to update certificates on report servers
