### ISSUE TITLE
Akvo.org vagrant box - mysql connection problem 

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#223]
As discussed over Skype my vagrant/virtual box isn't connecting to the mysql db for some reason.
It worked yesterday but as of today was no longer working. I tried 'vagrant destroy' and then downloading a fresh box but it's still not working.

Errors from sequelpro when trying to connect:
'Unable to connect to host homepage.localdev.akvo.org, or the request timed out.

Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).

MySQL said: Can't connect to MySQL server on 'homepage.localdev.akvo.org' (4)

Used command:  /usr/bin/ssh -v -N -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 MYUSER@homepage.localdev.akvo.org -L 49744/127.0.0.1/3306 -L 49745/homepage.localdev.akvo.org/3306

Bad local forwarding specification ' 49744/127.0.0.1/3306'

Vagrant up:

default: Attempting graceful shutdown of VM...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.2.0
    default: VirtualBox Version: 4.3
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/lMYUSER/Github/akvo-web/vagrant
    default: /vagrant/homepage/checkout => /Users/MYUSER/Github/akvo-web
==> default: Machine already provi
![screen shot 2015-10-22 at 12 04 46](https://cloud.githubusercontent.com/assets/2675262/10668723/e5c3a6f4-78dd-11e5-9604-9fdcd87ea57b.png)
![screen shot 2015-10-22 at 12 05 12](https://cloud.githubusercontent.com/assets/2675262/10668726/eb2980b4-78dd-11e5-8f71-686c8e0114ba.png)

sioned. Run `vagrant provision` or use the `--provision`
==> default: to force provisioning. Provisioners marked to run always will still run.

**Comment by orifito** [comment]
A fresh vagrant box has been provided, which solves that issue
