### ISSUE TITLE
Login for Mark, Marten & Geert on psql.test.akvo-ops.org

### ISSUE THREAD

**Issue by peeb** [akvo/akvo-provisioning#229]
@mtwestra, @mato74 and @geerts require login accounts on psql.test.akvo-ops.org for working on RSR data.

**Comment by mtwestra** [comment]
The idea is to create standard reports for RSR, using BIRT and the reportserver. In order to create the reports on local machines, access is needed on local machines to the test server RSR database.

**Comment by peeb** [comment]
Added `geert` to users module.

**Comment by peeb** [comment]
All three users now have login accounts in base provisioning.
