### ISSUE TITLE
Support page redirect - Akvo.org

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#231]
We need to redirect http://akvo.org/help/help-support/flow-help/ to http://flowsupport.akvo.org/ in line with using Support Hero for self-help/support pages.

**Comment by orifito** [comment]
Applied to test env, let me know when you are ok to do so at uat & live

**Comment by orifito** [comment]
@Lynngre should I add this redirect to uat & live?

**Comment by Lynngre** [comment]
@orifito  weird I didnt get these messages via email. Yes please set redirect as permanent for live asap.

**Comment by orifito** [comment]
@Lynngre permanent redirect applied in all environments
