### ISSUE TITLE
SSh for Lan (AkvoSites)

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#235]
Could you please setup an ssh account to the sites.akvotest.org server?

He also needs permissions to write to files in /akvosites/code dir.

https://github.com/tlandn.keys

He's going to be doing some Akvo sites work for us.

We have a CLA for him.

**Comment by orifito** [comment]
@Lynngre user `lan` has been added to sites.akvotest.org :tada:
