### ISSUE TITLE
Create a Docker containter for Akvo DASH python development

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-provisioning#246]
We're going to use Django as a way of exposing some _Models_ via the Django Rest Framework.
In the past we used a Vagrant Box for development but we're moving towards using Docker.

We need to prepare a `Dockerfile`, and documentation on how to use it, that describes an image for development. Initially will be just one image containing everything needed for development.

* django 1.9.1
* python 3
* postgres 9.5
* nginx

The current DASH repository is: https://github.com/akvo/akvo-dash

**Comment by zzgvh** [comment]
With docker, it makes sense to not have a virtualenv, right? If so then just having pip is enough I think. Eventually it'd be nice to have python libraries auto-install from a requirements file, but that's not needed initially. 

Not entirely sure about the version of python. 3.5 was released only a few months ago so there is a small chance of libraries not supporting it. 3.4 is over a year old and the conservative choice I guess.

**Comment by iperdomo** [comment]
Default versions in Ubuntu 14.04

* `python 3.4` - http://packages.ubuntu.com/trusty/python3
* `pip 1.5.4` http://packages.ubuntu.com/trusty/python-pip

**Comment by iperdomo** [comment]
> With docker, it makes sense to not have a virtualenv, right?

Yeah, the virtualenv is the workaround to have a self contained environment. In this case the whole image is the isolated environment.

**Comment by zzgvh** [comment]
Ah, well, then 3.4 seems like an obvious easy choice!

**Comment by kardan** [comment]
Do we need Nginx if it's only for development?

**Comment by zzgvh** [comment]
Good question. But given the time pressure we seem to have it's probably good if a dev server can be set up using this for demo purposes.

**Comment by kardan** [comment]
Issue in Dash repo: https://github.com/akvo/akvo-dash/issues/3
