### ISSUE TITLE
peak.akvo.org - http to https permanent redirect

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#250]
It seems wordpress 4.4. includes adding srcset with a change re responsive images. This means that anything stored as http is not displayed in posts/pages as it loads as 'http' which is not secure.  

Apparently the only way to fix this for previously installed sites is to add a permanent redirect.  So anything stored as http://peak.akvo.org is forced to forward to https://peak.akvo.org instead.

**Comment by Lynngre** [comment]
@orifito this one too please

**Comment by orifito** [comment]
@Lynngre just checked our nginx configuration for this virtual host. We already have a permanent redirect from http to https.
Could you give me more info on that issue?

**Comment by Lynngre** [comment]
thanks for checking that @orifito . It seems WP4.4+ has a bug related to responsive image attribute 'srcset' which does not set the image url as 'https' so the images don't load as they're classed as insecure.

I found a fix for now, hopefully WP will update this soon (although first issues were raised 2 years ago, but the bug is back).

Thankfully this happened on Peak but good to bear in mind for Akvo.org or Akvo Sites updating to SSL in the future.
