### ISSUE TITLE
Redirects walkingforwater

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#252]
http://www.walkingforwater.nl/ & http://www.walkingforwater.us/ should be redirected to http://www.walkingforwater.eu/ on the Akvofoundation.org server.

**Comment by Lynngre** [comment]
@orifito any news on this?

**Comment by orifito** [comment]
@Lynngre sorry, I haven't been able to find time to apply those redirects. I'll work on that and keep you posted

**Comment by orifito** [comment]
@Lynngre those redirects have been applied

**Comment by Lynngre** [comment]
@orifito thank you!
