### ISSUE TITLE
SSH access for akvo.org developer

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#260]
Samuel Thomas https://github.com/samvthom16

**Comment by orifito** [comment]
@Lynngre just configured the 'samuel' user for him. What servers do he need access to?

**Comment by Lynngre** [comment]
He only needs access to akvodev.org for now 93.191.132.54

**Comment by orifito** [comment]
Sorry missed your reply.. from now on he can access to akvodev.org
