### ISSUE TITLE
AkvoSites ZZ code deployment

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#262]
All code from https://github.com/akvo/akvo-sites-zz-template develop branch to be deployed to live.

**Comment by Lynngre** [comment]
@peeb I'm waiting for the go ahead from Harro & Christien as they're having a meeting with AfriAlliance to show them the Akvo Site sometime this week.  I'll ping you when it's ok to deploy this to live.

**Comment by Lynngre** [comment]
Meeting is first week of March, so if we could deploy the code asap to live that would be great.  Please ping me re possible day.

**Comment by peeb** [comment]
How about Friday 19/02?

**Comment by Lynngre** [comment]
@peeb yes, that would be great if we could push it in the morning in case of any issues.

**Comment by peeb** [comment]
@Lynngre code is deployed to test and live.

**Comment by Lynngre** [comment]
#262 completed
