### ISSUE TITLE
SSL on analytics.akvo.org

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#266]
Install SSL cert for Piwik to be set to use https:// instead of http://

**Comment by Lynngre** [comment]
And also this should include a redirect from http:// to https://

**Comment by iperdomo** [comment]
Habemus SSL
![analytics-ssl](https://cloud.githubusercontent.com/assets/178474/13269492/338c01ae-da88-11e5-9f08-e373a6df88f2.png)

**Comment by iperdomo** [comment]
I did a quick test on IE, Chrome and Firefox and they all follow the redirect when trying to fetch a JS resource. It seems that is safe to force the redirect from `http://` to `https://`.

![js-redirect-chrome](https://cloud.githubusercontent.com/assets/178474/13283095/72b8e73e-daec-11e5-9e36-0935e709037e.png)
![js-redirect-firefox](https://cloud.githubusercontent.com/assets/178474/13283096/72b9afde-daec-11e5-919d-c24eb34ad887.png)
![js-redirect-ie](https://cloud.githubusercontent.com/assets/178474/13283097/730593f4-daec-11e5-9b1c-3d8ab66692ba.png)

**Comment by iperdomo** [comment]
Enabled automatic redirect to https via [Redirect](https://wiki.apache.org/httpd/RedirectSSL) directive.
