### ISSUE TITLE
Deployment of Akvo Dash prototype using Docker

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-provisioning#271]
We want to use Docker to deploy the current (prototype) version of Akvo Dash.

There are 2 parts:

* client: it's just an `index.html` + `bundle.js` those can be served directly via nginx
* backend: it's a clojure application exposing some http endpoints (defaults to `http://localhost:3000/api`). 

The backend needs access to a PostgreSQL 9.4 service

**Comment by iperdomo** [comment]
@orifito in the `proxy` container we need to serve always `index.html` so the `/` location looks like this:

````
location / {
  root   /usr/share/nginx/html;
  try_files $uri $uri/ /index.html;
}
````

This is because the [SPA](https://en.wikipedia.org/wiki/Single-page_application) uses some special routing that doesn't exist physically, e.g.:

    http://host/library
    http://host/datasets
    http://host/visualisations

All those URLs are `index.html` behind the scenes.

**Comment by orifito** [comment]
@iperdomo cool, thanks for testing that!

**Comment by iperdomo** [comment]
@orifito i found a solution to my problem of not findind

**Comment by orifito** [comment]
@iperdomo great! I'll include that change :+1:
