### ISSUE TITLE
Increase upload limit of /media/db/iati_import/ folder in RSR

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-provisioning#277]
For the Cordaid import in RSR, they send us a large file (approx 120 MB) that we need to process. Our new IATI import allows for uploading that file, but the folder (```/media/db/iati_import/```) does not support uploads of more than 5 MB I think. Could this be increased to 150 MB or so, just for this folder?

And maybe for Test / UAT as well, while we're at it.

**Comment by peeb** [comment]
@orifito please close this issue if you're happy to do so.

**Comment by orifito** [comment]
@peeb sure, more than happy to close it :+1:

**Comment by punchagan** [comment]
@orifito @peeb the fix says it's temporary.  I was wondering, if this is going away soon, or if there's a better fix, or if this is stay as is for the foreseeable future?

**Comment by peeb** [comment]
The better fix would have to be discussed and should ideally be done on the RSR side - i.e. if you have "expensive" API endpoints, they should be paginated or limited in some way and dealt with on the client.

I personally see both caching and timeout increases as the last resort.

What I would propose would be auditing and fixing expensive API calls and then disabling this timeout hack.

@orifito  - thoughs?

**Comment by orifito** [comment]
Same than yours, paginating expensive API endpoints. Once it's done, we will be more than happy to remove such huge timeout.

**Comment by punchagan** [comment]
This is the `client_max_body_size` hack for file uploads/POSTs. But, I guess your comments still hold?

**Comment by orifito** [comment]
Ah I misread then... sorry! I guess that's no longer needed

**Comment by peeb** [comment]
I misread as well. Apologies!
