### ISSUE TITLE
Restore backup from Dec washalliance.nl

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-provisioning#289]
Recover the code and database from December backup

**Comment by Lynngre** [comment]
@iperdomo & @peeb just as an update.  Rumesh from Kominsky promises me he'll have the latest code for the old Akvo sites uploaded by no later than end of day Friday.

**Comment by peeb** [comment]
Thanks for the update @Lynngre

**Comment by Lynngre** [comment]
Washalliance.nl has migrated to a new site, no longer relevant.
