### ISSUE TITLE
Security on WordPress servers

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#290]
Work on hardening security on WordPress servers and WordPress installations themselves.  We need to do some research and planning around this.  For now I've installed a WP firewall plugin - but I don't think we should rely on a plugin to take care of all of the possible security holes.

**Comment by peeb** [comment]
@Lynngre can you confirm that the XML-RPC blocking plugin is also now part of the base set of plugins?

**Comment by Lynngre** [comment]
Yes the firewall handles that too.

**Comment by peeb** [comment]
OK great @Lynngre thanks.
