### ISSUE TITLE
Akvo sites ssh access for Samuel Thomas (WP developer)

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-provisioning#295]
ssh access to:  sites.akvotest.org
ssh access to:  akvofoundation.org

https://github.com/samvthom16
https://github.com/samvthom16.keys

We're migrating washalliance.nl from old Akvo Sites to new Akvo Sites.

Washalliance have requested many changes to the new theme to accommodate what they had in the old theme. Additionally they have a timeline, etc installed which is seperate from the theme itself  but resides on the server.

Samuel will be doing the changes/updates/migration needs that fall outside of what currently exists or is possible by Annabelle or myself.

As there's no continuous deployment Sam needs access via ssh to sites.akvotest.org (for testing).
He will then push any changes made to the new Akvo Sites repo.

As Sam is not familiar with the old theme code, it would be good if he could access the server via ssh as we're still not sure everything resides in the old repo & he needs access to the timeline installation.

**Comment by peeb** [comment]
User `samuel` is already in puppet provisioning with the correct ssh key.

I'll verify if he can login to the relevant servers and if not, reprovision them.

**Comment by peeb** [comment]
User `samuel` should be able to login with ssh already. Please ask him to try and update this issue accordingly.

**Comment by peeb** [comment]
I will make sure he is able to access the `/var/akvo/akvosites` dir.

**Comment by peeb** [comment]
@Lynngre there is, however, no account for `samuel` on live2 (akvofoundation.org) so this will need to be reprovisioned. I will update when this is done.

**Comment by Lynngre** [comment]
Thanks @peeb will followup with @samvthom16

**Comment by samvthom16** [comment]
@peeb Sorry for the confusion. Had to create a new private and public key. 

Please find my new public key here:
https://github.com/samvthom16.keys

**Comment by peeb** [comment]
OK thanks @samvthom16 - I'll reprovision both of those machines with the new ssh key.

**Comment by peeb** [comment]
sites.akvotest.org is provisioned with the new key

**Comment by Lynngre** [comment]
@peeb it seems @samvthom16 has no write permissions on sites.akvotest.org, we need him to be able to write files within /code.

**Comment by peeb** [comment]
@samvthom16 is now a member of group www-edit on sites.akvotest.org.

**Comment by Lynngre** [comment]
Thanks @peeb

**Comment by Lynngre** [comment]
@peeb @samvthom16 still has no write permissions even in group www-edit.  He needs to be able to create/change/execute files on the test server. sites.akvotest.org

**Comment by peeb** [comment]
I can't give @samvthom16 him root permissions for obvious reasons, so I will need an itinerary of what **directories** need to be created and where.

Then I can give him read/write/execute permissions on those directories.

**Comment by Lynngre** [comment]
He needs to have 'sudo' access on everything under /var/akvo/akvosites/code

**Comment by peeb** [comment]
OK
