### ISSUE TITLE
Replacement akvofoundation.org certificate

### ISSUE THREAD

**Issue by peeb** [akvo/akvo-provisioning#299]
To deploy new CartoDB capacity we need to support the following domain name pattern:

```
*.*.akvotest.org
```

to support, for example, `instance-x.cartodb.akvotest.org`.

Please can we request that Comodo regenerate our certificate to include this?

@Lynngre

**Comment by Lynngre** [comment]
@peeb I need a new csr file including all 16 domains & subdomains included originally plus the new domain to be added.
Cost is $156 for the additional domain

**Comment by Lynngre** [comment]
*.akvotest.org is already added to the cert.
We cannot purchase *.*.akvotest.org

**Comment by Lynngre** [comment]
*.cartodb.akvotest.org & *.cartodb2.akvotest.org have been included in the cert.

**Comment by peeb** [comment]
Awesome thanks

**Comment by peeb** [comment]
This cert is now installed on `cartodb2.akvotest.org` and will be added to `cartodb.akvotest.org` shortly.

I will create a separate issue to add it to our general provisioning setup.

Closing this issue.
