### ISSUE TITLE
Block Google from Indexing our RSR Development Environments

### ISSUE THREAD

**Issue by KasperBrandt** [akvo/akvo-provisioning#79]
We should add a robots.txt to all NON LIVE machines that prevents Google from indexing the site and displaying the content in search results.

This looks to be pretty simple: https://support.google.com/webmasters/answer/156449?rd=1

**Comment by KasperBrandt** [comment]
@orifito I think our test servers are probably still indexed, right? Any clue what to do in RSR to prevent it? I'm guessing something like:

**live-robots.txt**
```User-agent: *
Allow: /```

**dev-robots.txt**
```User-agent: *
Disallow: /```

Correct?

**Comment by orifito** [comment]
@KasperBrandt yes, they are still being indexed... 
Those simple robots.txt should be fine, let's coordinate to update nginx configuration (if needed)
